@startuml
actor "user (browser)" as user
participant "authorization server (google)" as auth
participant "client (slide deck)" as client
participant "resource (google calendar)" as resource

user -> auth: clicks "login with google"
auth -> user: login form
user -> auth: send username + password
auth -> client: redirect with token
client -> resource: access resource
@enduml