== Task 3 - solution


POST https://devjourfix-willhaben-test.auth.eu-central-1.amazoncognito.com/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NXZra25pc2VkczRpMXM0cHN0MHVvZTI4MHU6MXIxbGtxZWE1dHVoNHNjbTdsa2Q0Mm1jbDMycGdyYnBraW01Z3ZzcDZidmduZTdlNTVmNw==

refresh_token=eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.Cfk1HahJSbiR4-PopqD-slVx_ZX0tGgGmQpDzwUKEz6mNAqzItun7dnErhLdiQQb_xOvhZmqTkvNPyOnPRoE1gRPoP0YvicLCDLSSN1cjPqF73QIgb1fLlPo5kbi3V57TEevfTxLZ_L2WzNhL5czsQtLuX-xfrSuUykJr4_lJYgFahFf0wM9OGg0WEKMyrt3wwDuq1Sff1AaTgm9YAS1B3cC3x9ncPYeefKc_uLYMF9SI5wGqMdfa4Q6D13swPQv6iUgJFpMviha76PgnLx9837IWzT1Ga_kFlkMpdC93X-3jNxqseOgTvspHeYh_ExZHmJGQVbG138jqCAM-tY9BA.GsS7iIbgDuagM7wa.51Bs3CjJP3_0DGj6U20AkpnbSOWwnScdY8VuSEdPyhET9R0cHCRNhx7oeSHRjZJNCJyeUkO2K8n0DQsOJ2y1B-g48FxDjEKs_kHCU7x0GbCqqOyrkRBVjSfLoujAiZVTTflzjNqga66JNZhULmKb8NCV4dQiKGdcPlI8w9UEWDauZf3xB5LL0-FD0OH9lA8fxQVTg0I-8sZe_WBYDl2lbgU8Pwwlu16OszAa9XOhMb8xJ-6biynJVl2A94BcekvlIfdqPOO3-ux9Eixd1J6UUgHabP5bAX6n0HLAEwnSbhhkjWku-M_uWhZFi33Hu9awfHPLqPO1IGYLbwbx0NfWoGJTxNao9kG7Fnqp8iMQAx9KTL8I8UkmOyeQkGB-YdG8ah_Ne0Kz9GGb4zzLi7AJ91NQuLjUeF_euedc1shWZXpHjqB3D1ZgcJuzDnhPBoAjMQc4olEmWV4iCIx_UOgjcG9Kv8ctjV9QUh8y8-WUWMQYYd9SfLYEOSnpxm6jcO0ZrMOEVdecv7kulM7m6hVU09iyoW-j9HWNX6h3RlITtS_zqjgYBY6AI1AVKsMiFuHf9fo7YIH75qfv_lBGeyhcxjdU9sM5fS1rTFT_dERqZRlxLD2AMTc1FumX2hThOo1OsYCf6yKnfTGe8G7tCLpRvcJSN0r78BpiTtFiuCBAExtOH1xfsIvAOPJQpGc9JHUcB_NrDI4QRtzGcyKWQikp3oIl8kiWrfvImFgu53csaTthKdeHo1UMPYU6G8qI5QiZ8YatMpPAtSW2lmrmssWFlI0zkCVijGyol4mAStyhSOfJSGObgJ9uaIiYrcCyGpCbwIZLk3bAejucm7rF03RjSAPD8QX-R-Xd8PIjeFzUy4PckahBeCKUw7cmWYla3iYqiOo6oWPK3GEGNY0VkoT5c4Chpaqba9HoSRev7UWsQux6VbtDJgl8dmJa_J-kfutB0NvmPeq3VRrclaVXhKue5mXRTBVMgo5ZDTzLnJZhV7e8vMwk2a5JD9bV0lQbAIYh4QAu-HGCIe_9rfDTGgTTXy-dxaQsM26Z28TtJvrN3IJd6qPj1prW9rJcirZkySexpZU2z4Ujhy-2PCT9LL0QeFOXSjC-t0X076oQcA_kLvdEzXhKUoJbrUmD0ng7z2zT_DRO0gTlz-wX6zJfS4FaM6XxMUZQ5M08e0OMf6FsKOvPwPA4Q9YcfPnuzkXvk-ZjPMa2tmyTn1lkO4lTa8IwKyh6F7MkZe51h-Tme25kSSAlNqonJ6EvJR9PNdmssRT0RVAUkfbrFOSbuDeE0vroxlM_Kb09vn2nmbv7UEAd2dY8vR1eDG3oNE6DHYpldVjMCjPxrj-H63ynz240JNWqH7s.5eTQb_vUktYyfiRL853ihQ&grant_type=refresh_token&client_id=5vkkniseds4i1s4pst0uoe280u
