== Task 2 - Authorization Code Flow

For this task, we use another process to obtain the access token:
https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[Authorization Code Flow].

We use the same authorization server, but to init the flow we use a different endpoint:

 https://devjourfix-willhaben-test.auth.eu-central-1.amazoncognito.com/login

For this flow, you have to use a different set of parameters:

.Query Parameters
|===

|`client_id` | `5vkkniseds4i1s4pst0uoe280u`

|`redirect_uri` | `http://localhost:8080/callback`

|`scope` | ? + `devjourfix.willhaben.test/devjourfix`

|`response_type` | ? |

|===

Again, fill in the missing query parameters (?) required by the https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint[standard]
and build a link.

Once you logged in, the server redirects you with a `code` query parameter.

This `code` can be exchanged for an *access token* using
the https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint[token endpoint]:

 https://devjourfix-willhaben-test.auth.eu-central-1.amazoncognito.com/oauth2/token

This request must be a HTTP POST and include specific *headers* and *request body*:

.Headers
|===

| Content-Type | `application/x-www-form-urlencoded`
| Authorization | `Base64Encode(client_id + ':' + client_secret)`

|===

The  `client_secret` needed to build the `Authorization` header is

 1r1lkqea5tuh4scm7lkd42mcl32pgrbpkim5gvsp6bvgne7e55f7


.Request Body
|===

| code | from previous request
| grant_type | ?
| client_id | ?
| redirect_uri | ?

|===

See also: https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html[authorization servers documentation].


To complete the task, use the `access_token` to access this resource

 https://5ddwj6qy0l.execute-api.eu-central-1.amazonaws.com/prod/task2

